apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource-sizing-service-single
  namespace: load-testing
  labels:
    app: resource-sizing-service
    version: v1
    deployment-type: single-pod-reference
spec:
  replicas: 1  # Single replica - VPA optimized configuration (REFERENCE)
  selector:
    matchLabels:
      app: resource-sizing-service
      deployment-type: single-pod-reference
  template:
    metadata:
      labels:
        app: resource-sizing-service
        version: v1
        deployment-type: single-pod-reference
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
      - name: resource-sizing-service
        image: resource-sizing-service:latest
        imagePullPolicy: Never  # Use local image for Docker Desktop
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "kubernetes"
        - name: JAVA_OPTS
          value: "-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0 -XX:+UseG1GC -Xms64m"
        resources:
          requests:
            memory: "380Mi"   # VPA-optimized: Proven optimal for single pod
            cpu: "250m"       # VPA-optimized: Handles startup and steady-state perfectly
          limits:
            memory: "600Mi"   # Conservative limit above VPA lower bound
            cpu: "500m"       # VPA upper bound recommendation
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 10
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
          readOnly: true
      volumes:
      - name: config-volume
        configMap:
          name: resource-sizing-config
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
