apiVersion: v1
kind: Service
metadata:
  name: resource-sizing-service
  namespace: load-testing
  labels:
    app: resource-sizing-service
    component: backend
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/actuator/prometheus"
spec:
  type: NodePort
  ports:
  - name: http
    port: 8080
    targetPort: http
    protocol: TCP
    nodePort: 30080  # Fixed NodePort for consistent testing
  selector:
    app: resource-sizing-service
