# ServiceMonitor for Spring Boot resource sizing service
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: resource-sizing-service
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: resource-sizing-service
  namespaceSelector:
    matchNames:
      - load-testing
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 5s
