recommender:
  resources:
    requests:
      cpu: 50m
      memory: 200Mi
    limits:
      cpu: 200m
      memory: 400Mi

updater:
  resources:
    requests:
      cpu: 25m
      memory: 100Mi
    limits:
      cpu: 100m
      memory: 200Mi

admissionController:
  resources:
    requests:
      cpu: 25m
      memory: 100Mi
    limits:
      cpu: 100m
      memory: 200Mi
