version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: resource-sizing-service
    ports:
      - "8080:8080"
    environment:
      # Spring profiles
      - SPRING_PROFILES_ACTIVE=docker
      # Application configuration
      - APP_EMPLOYEE_DEFAULT_COUNT=100
      - APP_EMPLOYEE_DEFAULT_STRING_SIZE=512
      # Memory simulation configuration
      - APP_MEMORY_CACHE_TTL_SECONDS=300
      - APP_MEMORY_CACHE_MAX_SIZE=1000
      - APP_MEMORY_SCENARIOS_LIGHT_COUNT=50
      - APP_MEMORY_SCENARIOS_LIGHT_STRING_SIZE=256
      - APP_MEMORY_SCENARIOS_MEDIUM_COUNT=200
      - APP_MEMORY_SCENARIOS_MEDIUM_STRING_SIZE=1024
      - APP_MEMORY_SCENARIOS_HEAVY_COUNT=500
      - APP_MEMORY_SCENARIOS_HEAVY_STRING_SIZE=4096
      - APP_MEMORY_SCENARIOS_EXTREME_COUNT=1000
      - APP_MEMORY_SCENARIOS_EXTREME_STRING_SIZE=8192
      # JVM options for container
      - JAVA_OPTS=-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0 -XX:+UseG1GC -Xms128m
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
